[build]
  command = "npm run netlify-build"
  publish = "dist/dev-digest/browser"

[[plugins]]
  package = "@netlify/plugin-labs"

[build.environment]
  NODE_VERSION = "18.0.0"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
