[build]
  command = "npm run build"
  publish = "dist/dev-digest/browser"

[build.environment]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
  PUPPETEER_CACHE_DIR = "/opt/buildhome/.cache/puppeteer"
  NODE_VERSION = "20"
